CREATE TABLE LOGINHISTORY(
    idx NUMBER PRIMARY KEY,
    id VARCHAR2(400) NOT NULL,
    retry NUMBER NOT NULL,
    lastFailedLogin NUMBER NOT NULL,
    lastSuccessedLogin NUMBER NOT NULL,
    clientIp varchar2(20) NOT NULL,
    sessionId varchar2(400) NOT NULL
)

CREATE SEQUENCE LOGINHISTORY_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;
